name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure Tests CMake
      run: cmake -S ${{github.workspace}}/Tests -B ${{github.workspace}}/Tests/cmake-build-debug -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build Tests
      working-directory: ${{github.workspace}}/Tests
      run: cmake --build ${{github.workspace}}/Tests/cmake-build-debug --config ${{env.BUILD_TYPE}}

    - name: Tests
      working-directory: ${{github.workspace}}/Tests/cmake-build-debug
      run: ./Tests

    - name: Send mail
      if: failure()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp-relay.sendinblue.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
        body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
        to: ximtech@inbox.lv
        from: Github CI
